export const ADD_COMMENT_FORM = 'ADD_COMMENT_FORM';
export const ADD_COMMENT_FORM_SUBMIT = 'ADD_COMMENT_FORM_SUBMIT';
export const ADD_COMMENT_FORM_FAILURE = 'ADD_COMMENT_FORM_FAILURE';
export const ADD_COMMENT_FORM_SUCCESS = 'ADD_COMMENT_FORM_SUCCESS';