export const ADD_ORDER_FORM = 'ADD_ORDER_FORM';
export const ADD_ORDER_FORM_SUBMIT = 'ADD_ORDER_FORM_SUBMIT';
export const ADD_ORDER_FORM_FAILURE = 'ADD_ORDER_FORM_FAILURE';
export const ADD_ORDER_FORM_SUCCESS = 'ADD_ORDER_FORM_SUCCESS';