export const EDIT_PROFILE_FORM = 'EDIT_PROFILE_FORM';
export const EDIT_PROFILE_FORM_SUBMIT = 'EDIT_PROFILE_FORM_SUBMIT';
export const EDIT_PROFILE_FORM_FAILURE = 'EDIT_PROFILE_FORM_FAILURE';
export const EDIT_PROFILE_FORM_SUCCESS = 'EDIT_PROFILE_FORM_SUCCESS';