export const SIGN_UP_FORM = 'SIGN_UP_FORM';
export const SIGN_UP_FORM_SUBMIT = 'SIGN_UP_FORM_SUBMIT';
export const SIGN_UP_FORM_FAILURE = 'SIGN_UP_FORM_FAILURE';
export const SIGN_UP_FORM_SUCCESS = 'SIGN_UP_FORM_SUCCESS';