export const SIGN_IN_FORM = 'SIGN_IN_FORM';
export const SIGN_IN_FORM_SUBMIT = 'SIGN_IN_FORM_SUBMIT';
export const SIGN_IN_FORM_FAILURE = 'SIGN_IN_FORM_FAILURE';
export const SIGN_IN_FORM_SUCCESS = 'SIGN_IN_FORM_SUCCESS';